// LOCAL VARIABLE DECLARATIONS
.section data1

// PROGRAM INSTRUCTIONS
.section program

// void TurnOnHeat_ASM(COFFEEPOT_DEVICE *coffeePot_BaseAddress, unsigned char heaterLevel, unsigned char heaterBoost);
.global _TurnOnHeat_ASM;

// INPUT PARAMETERS
#define PAR1_R0 R0
#define PAR2_R1 R1
#define PAR3_R2 R2

// TEMPORARY REGISTERS
#define TEMP_R3 R3
#define TEMP_R4 R4

// COFFEEPOT_DEVICE * BaseAddress
#define COFFEEPOT_DEVICE_P0 P0

// CONTROL REGISTER OFFSETS
#define CONTROLREGISTER_OFFSET	0
#define WATERINFLOWREGISTER_OFFSET 	7
#define HEATERREGISTER_OFFSET	6
#define HEATERBOOST_OFFSET		8
#define LED_OFFSET				12

// CONTROL BITMASKS
#define INITPOWERED				(1 << 0)
#define LEDPOWER				(1 << 1)
#define	WATERPOWER				(1 << 2)
#define HEATERPOWER				(1 << 3)
#define DEVICEREADY				(1 << 4)

// LED BITMASKS
#define LED1						(1 << (LED_OFFSET + 0))
#define LED2						(1 << (LED_OFFSET + 1))
#define LED3						(1 << (LED_OFFSET + 2))
#define LED4						(1 << (LED_OFFSET + 3))
#define LED_LED_ON					LED2
#define LED_HEAT_ON					LED3
#define LED_WATER_ON				LED4

_TurnOnHeat_ASM:

LINK 20;

// SET COFFEE POT BASE ADDRESS
	COFFEEPOT_DEVICE_P0 = PAR1_R0;
	
// TURN WATER OFF - **DOES NOT WORK WITH GUI
	//TEMP_R4 = ~WATERPOWER;
	//TEMP_R3 = TEMP_R3 & TEMP_R4;
	//R4.L = lo(~LED_WATER_ON);	R4.H = hi(~LED_WATER_ON);
	//TEMP_R3 = TEMP_R3 & TEMP_R4;
	
// TURN WATER FLOW RATE DOWN TO ZERO - **WORKS WITH GUI
	TEMP_R3 = 0;
	B[COFFEEPOT_DEVICE_P0 + WATERINFLOWREGISTER_OFFSET] = TEMP_R3;
	
// SET HEATER AND BOOST LEVEL
	B[COFFEEPOT_DEVICE_P0 + HEATERREGISTER_OFFSET] = PAR2_R1;
	B[COFFEEPOT_DEVICE_P0 + HEATERBOOST_OFFSET] = PAR3_R2;
	
// TURN ON HEAT (AND LED)
	TEMP_R3 = W[COFFEEPOT_DEVICE_P0 + CONTROLREGISTER_OFFSET];
	TEMP_R4 = HEATERPOWER;
	TEMP_R3 = TEMP_R3 | TEMP_R4;
	R4.L = lo(LED_HEAT_ON);		R4.H = hi(LED_HEAT_ON);
	TEMP_R3 = TEMP_R3 | TEMP_R4;
	W[COFFEEPOT_DEVICE_P0 + CONTROLREGISTER_OFFSET] = TEMP_R3;

// UPDATE DISPLAY
	.extern __Z23UpdateSimulationDisplayv;
	CALL __Z23UpdateSimulationDisplayv;
	CALL __Z23UpdateSimulationDisplayv;

UNLINK;

_TurnOnHeat_ASM.END:

RTS;
